[project]
name = "vommit"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Robin van der Noord", email = "robinvandernoord@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "configuraptor >= 2.5.4, < 3",
    "ewok",
    "keyring",
    "packaging",
    "questionary >= 2, < 3",
    "rich",
    "tomlkit",
]

[project.scripts]
vommit = "vommit.cli:program.run"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[project.entry-points.edwh]
vommit = "vommit.tasks"

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = [
    "src",
]

[tool.ruff]
include = [
    "src/**/*.py",
]

[tool.ruff.lint]
ignore = [
    "RUF012", # ClassVar changes runtime behavior
]

[tool.ty.src]
include = [
    "src",
]

[tool.coverage.report]
exclude_also = [
    '\A(?s:.*# pragma: exclude file.*)\Z',
]


[tool.su6]
directory = "src"

coverage = 100
badge = "coverage.svg"

[tool.vommit]
allow_breaking_bang = true
allow_breaking_footer = true
prerelease_token = "beta"

[tool.vommit.git]
enabled = true
origin = "origin"
branch = "vommit/staging"
on_wrong_branch = "error"
tag_format = "v{version}"
commit_format = "{version}"

[tool.vommit.changelog]
enabled = true
file = "CHANGELOG.md"
placeholder = "<!-- next-version-placeholder -->"
placeholder_regex = "^<!\\-\\-\\s*next\\-version\\-placeholder\\s*\\-\\->$"
entry_title_format = "## v{version} ({date:%Y-%m-%d})"
include_prereleases = false

[tool.vommit.changelog.levels]
break = "Breaking Change{s}"
feat = "Feature{s}"
fix = "Fix{es}"
perf = "Performance"
docs = "Documentation"

[tool.vommit.pypi]
enabled = true
use_keyring = true

[tool.vommit.commands]
clean = "rm -rf ./dist"
build = "uv build"
publish = "uv publish"
release = "{clean} && {build} && {publish}"

[tool.vommit.version_bump_map]
break = "major"
feat = "minor"
fix = "patch"
perf = "patch"
docs = "patch"



