[project]
name = "vommit"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Robin van der Noord", email = "robinvandernoord@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ewok",
    "tomlkit",
]

[project.scripts]
vommit = "vommit.cli:program.run"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[project.entry-points.edwh]
vommit = "vommit.tasks"

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = [
    "src",
]

[tool.coverage.report]
exclude_also = [
    '\A(?s:.*# pragma: exclude file.*)\Z',
]


[tool.su6]
coverage = 100
badge = "coverage.svg"
